export const data = [
    {
        name:'raj',
        country:'india',
        state:'gujarat',
        city:'surat',
        category:'A'
    },
    {
        name:'meet',
        country:'uk',
        state:'london',
        city:'calefornia',
        category:'A'
    },
    {
        name:'jeet',
        country:'india',
        state:'rajasthan',
        city:'jaipur',
        category:'C'
    },
    {
        name:'sagar',
        country:'pakistan',
        state:'punjab',
        city:'lahore',
        category:'B'
    }
]